-- 1. 시퀀스 생성
CREATE SEQUENCE seq_user_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_board_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_post_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_image_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_comments_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_community_post_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_like_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_favorite_id START WITH 1 INCREMENT BY 1 NOCACHE;