spring.application.name=usedtrade

spring.output.ansi.enabled=always

logging.level.root=info
logging.level.com.pknu26.usedtrade.mapper=debug
logging.level.org.mybatis=debug
logging.level.java.sql=debug

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=admin
spring.datasource.password=1234

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.pknu26.usedtrade.dto
mybatis.configuration.map-underscore-to-camel-case=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-http-form-post-size=200MB
server.tomcat.max-swallow-size=200MB

# 로그인 세션 시간을 1시간으로 변경
server.servlet.session.timeout=60m

# mac이라 이렇게 변경 ## nahyeon
# file.upload-dir=/Users/nahyeon/Projects/java-miniproject-2026/usedtrade/uploads/
file.upload-dir=D:/miniproject/usedtrade/uploads/

## Thymeleaf 설정 - 개발때만 추가
spring.thymeleaf.cache=false